USE [baseproject]
GO


INSERT INTO Pais VALUES('Afeganistão       ',1)               
INSERT INTO Pais VALUES('África do Sul',1)
INSERT INTO Pais VALUES('Akrotiri',1)
INSERT INTO Pais VALUES('Albânia',1)
INSERT INTO Pais VALUES('Alemanha',1)
INSERT INTO Pais VALUES('Andorra',1)
INSERT INTO Pais VALUES('Angola',1)
INSERT INTO Pais VALUES('Anguila',1)
INSERT INTO Pais VALUES('Antárctida',1)
INSERT INTO Pais VALUES('Antígua e Barbuda',1)
INSERT INTO Pais VALUES('Antilhas Neerlandesas',1)
INSERT INTO Pais VALUES('Arábia Saudita',1)
INSERT INTO Pais VALUES('Arctic Ocean',1)
INSERT INTO Pais VALUES('Argélia',1)
INSERT INTO Pais VALUES('Argentina',1)
INSERT INTO Pais VALUES('Arménia',1)
INSERT INTO Pais VALUES('Aruba',1)
INSERT INTO Pais VALUES('Ashmore and Cartier Islands',1)
INSERT INTO Pais VALUES('Atlantic Ocean',1)
INSERT INTO Pais VALUES('Austrália',1)
INSERT INTO Pais VALUES('Áustria',1)
INSERT INTO Pais VALUES('Azerbaijão',1)
INSERT INTO Pais VALUES('Baamas',1)
INSERT INTO Pais VALUES('Bangladeche',1)
INSERT INTO Pais VALUES('Barbados',1)
INSERT INTO Pais VALUES('Barém',1)
INSERT INTO Pais VALUES('Bélgica',1)
INSERT INTO Pais VALUES('Belize',1)
INSERT INTO Pais VALUES('Benim',1)
INSERT INTO Pais VALUES('Bermudas',1)
INSERT INTO Pais VALUES('Bielorrússia',1)
INSERT INTO Pais VALUES('Birmânia',1)
INSERT INTO Pais VALUES('Bolívia',1)
INSERT INTO Pais VALUES('Bósnia e Herzegovina',1)
INSERT INTO Pais VALUES('Botsuana',1)
INSERT INTO Pais VALUES('Brasil',1)
INSERT INTO Pais VALUES('Brunei',1)
INSERT INTO Pais VALUES('Bulgária',1)
INSERT INTO Pais VALUES('Burquina Faso',1)
INSERT INTO Pais VALUES('Burúndi',1)
INSERT INTO Pais VALUES('Butão',1)
INSERT INTO Pais VALUES('Cabo Verde',1)
INSERT INTO Pais VALUES('Camarões',1)
INSERT INTO Pais VALUES('Camboja',1)
INSERT INTO Pais VALUES('Canadá',1)
INSERT INTO Pais VALUES('Catar',1)
INSERT INTO Pais VALUES('Cazaquistão',1)                                           
INSERT INTO Pais VALUES('Chade',1)
INSERT INTO Pais VALUES('Chile',1)
INSERT INTO Pais VALUES('China',1)
INSERT INTO Pais VALUES('Chipre',1)
INSERT INTO Pais VALUES('Clipperton Island',1)
INSERT INTO Pais VALUES('Colômbia',1)
INSERT INTO Pais VALUES('Comores',1)
INSERT INTO Pais VALUES('Congo-Brazzaville',1)
INSERT INTO Pais VALUES('Congo-Kinshasa',1)
INSERT INTO Pais VALUES('Coral Sea Islands',1)
INSERT INTO Pais VALUES('Coreia do Norte',1)
INSERT INTO Pais VALUES('Coreia do Sul',1)
INSERT INTO Pais VALUES('Costa do Marfim',1)
INSERT INTO Pais VALUES('Costa Rica',1)
INSERT INTO Pais VALUES('Croácia',1)
INSERT INTO Pais VALUES('Cuba',1)
INSERT INTO Pais VALUES('Dhekelia',1)
INSERT INTO Pais VALUES('Dinamarca',1)
INSERT INTO Pais VALUES('Domínica',1)
INSERT INTO Pais VALUES('Egipto',1)
INSERT INTO Pais VALUES('Emiratos Árabes Unidos',1)
INSERT INTO Pais VALUES('Equador',1)
INSERT INTO Pais VALUES('Eritreia',1)
INSERT INTO Pais VALUES('Eslováquia',1)
INSERT INTO Pais VALUES('Eslovénia',1)
INSERT INTO Pais VALUES('Espanha',1)
INSERT INTO Pais VALUES('Estados Unidos',1)
INSERT INTO Pais VALUES('Estónia',1)
INSERT INTO Pais VALUES('Etiópia',1)
INSERT INTO Pais VALUES('Faroé',1)
INSERT INTO Pais VALUES('Fiji',1)
INSERT INTO Pais VALUES('Filipinas',1)
INSERT INTO Pais VALUES('Finlândia',1)
INSERT INTO Pais VALUES('França',1)
INSERT INTO Pais VALUES('Gabão',1)
INSERT INTO Pais VALUES('Gâmbia',1)
INSERT INTO Pais VALUES('Gana',1)
INSERT INTO Pais VALUES('Gaza Strip',1)
INSERT INTO Pais VALUES('Geórgia',1)
INSERT INTO Pais VALUES('Geórgia do Sul e Sandwich do Sul',1)
INSERT INTO Pais VALUES('Gibraltar',1)
INSERT INTO Pais VALUES('Granada',1)
INSERT INTO Pais VALUES('Grécia',1)
INSERT INTO Pais VALUES('Gronelândia',1)
INSERT INTO Pais VALUES('Guame',1)
INSERT INTO Pais VALUES('Guatemala',1)
INSERT INTO Pais VALUES('Guernsey',1)
INSERT INTO Pais VALUES('Guiana',1)
INSERT INTO Pais VALUES('Guiné',1)
INSERT INTO Pais VALUES('Guiné Equatorial',1)
INSERT INTO Pais VALUES('Guiné-Bissau',1)
INSERT INTO Pais VALUES('Haiti',1)
INSERT INTO Pais VALUES('Honduras',1)
INSERT INTO Pais VALUES('Hong Kong',1)
INSERT INTO Pais VALUES('Hungria',1)
INSERT INTO Pais VALUES('Iémen',1)
INSERT INTO Pais VALUES('Ilha Bouvet                              ',1)
INSERT INTO Pais VALUES('Ilha do Natal                            ',1)
INSERT INTO Pais VALUES('Ilha Norfolk                             ',1)
INSERT INTO Pais VALUES('Ilhas Caimão                             ',1)
INSERT INTO Pais VALUES('Ilhas Cook                               ',1)
INSERT INTO Pais VALUES('Ilhas dos Cocos                          ',1)
INSERT INTO Pais VALUES('Ilhas Falkland                           ',1)
INSERT INTO Pais VALUES('Ilhas Heard e McDonald                   ',1)
INSERT INTO Pais VALUES('Ilhas Marshall                           ',1)
INSERT INTO Pais VALUES('Ilhas Salomão                            ',1)
INSERT INTO Pais VALUES('Ilhas Turcas e Caicos                    ',1)
INSERT INTO Pais VALUES('Ilhas Virgens Americanas                 ',1)
INSERT INTO Pais VALUES('Ilhas Virgens Britânicas                 ',1)
INSERT INTO Pais VALUES('Índia                                    ',1)
INSERT INTO Pais VALUES('Indian Ocean                             ',1)
INSERT INTO Pais VALUES('Indonésia                                ',1)
INSERT INTO Pais VALUES('Irão                                     ',1)
INSERT INTO Pais VALUES('Iraque                                   ',1)
INSERT INTO Pais VALUES('Irlanda                                  ',1)
INSERT INTO Pais VALUES('Islândia                                 ',1)
INSERT INTO Pais VALUES('Israel                                   ',1)
INSERT INTO Pais VALUES('Itália                                   ',1)
INSERT INTO Pais VALUES('Jamaica                                  ',1)
INSERT INTO Pais VALUES('Jan Mayen                                ',1)
INSERT INTO Pais VALUES('Japão                                    ',1)
INSERT INTO Pais VALUES('Jersey                                   ',1)
INSERT INTO Pais VALUES('Jibuti                                   ',1)
INSERT INTO Pais VALUES('Jordânia                                 ',1)
INSERT INTO Pais VALUES('Kuwait                                   ',1)
INSERT INTO Pais VALUES('Laos                                     ',1)
INSERT INTO Pais VALUES('Lesoto                                   ',1)
INSERT INTO Pais VALUES('Letónia                                  ',1)
INSERT INTO Pais VALUES('Líbano                                   ',1)
INSERT INTO Pais VALUES('Libéria                                  ',1)
INSERT INTO Pais VALUES('Líbia                                    ',1)
INSERT INTO Pais VALUES('Listenstaine                             ',1)
INSERT INTO Pais VALUES('Lituânia                                 ',1)
INSERT INTO Pais VALUES('Luxemburgo                               ',1)
INSERT INTO Pais VALUES('Macau                                    ',1)
INSERT INTO Pais VALUES('Macedónia                                ',1)
INSERT INTO Pais VALUES('Madagáscar                               ',1)
INSERT INTO Pais VALUES('Malásia                                  ',1)
INSERT INTO Pais VALUES('Malávi                                   ',1)
INSERT INTO Pais VALUES('Maldivas                                 ',1)
INSERT INTO Pais VALUES('Mali                                     ',1)
INSERT INTO Pais VALUES('Malta                                    ',1)
INSERT INTO Pais VALUES('Man, Isle of                             ',1)
INSERT INTO Pais VALUES('Marianas do Norte                        ',1)
INSERT INTO Pais VALUES('Marrocos                                 ',1)
INSERT INTO Pais VALUES('Maurícia                                 ',1)
INSERT INTO Pais VALUES('Mauritânia                               ',1)
INSERT INTO Pais VALUES('Mayotte                                  ',1)
INSERT INTO Pais VALUES('México                                   ',1)
INSERT INTO Pais VALUES('Micronésia                               ',1)
INSERT INTO Pais VALUES('Moçambique                               ',1)
INSERT INTO Pais VALUES('Moldávia                                 ',1)
INSERT INTO Pais VALUES('Mónaco                                   ',1)
INSERT INTO Pais VALUES('Mongólia                                 ',1)
INSERT INTO Pais VALUES('Monserrate                               ',1)
INSERT INTO Pais VALUES('Montenegro                               ',1)
INSERT INTO Pais VALUES('Mundo                                    ',1)
INSERT INTO Pais VALUES('Namíbia                                  ',1)
INSERT INTO Pais VALUES('Nauru                                    ',1)
INSERT INTO Pais VALUES('Navassa Island                           ',1)
INSERT INTO Pais VALUES('Nepal                                    ',1)
INSERT INTO Pais VALUES('Nicarágua                                ',1)
INSERT INTO Pais VALUES('Níger                                    ',1)
INSERT INTO Pais VALUES('Nigéria                                  ',1)
INSERT INTO Pais VALUES('Niue                                     ',1)
INSERT INTO Pais VALUES('Noruega                                  ',1)
INSERT INTO Pais VALUES('Nova Caledónia                           ',1)
INSERT INTO Pais VALUES('Nova Zelândia                            ',1)
INSERT INTO Pais VALUES('Omã                                      ',1)
INSERT INTO Pais VALUES('Pacific Ocean                            ',1)
INSERT INTO Pais VALUES('Países Baixos                            ',1)
INSERT INTO Pais VALUES('Palau                                    ',1)
INSERT INTO Pais VALUES('Panamá                                   ',1)
INSERT INTO Pais VALUES('Papua-Nova Guiné                         ',1)
INSERT INTO Pais VALUES('Paquistão                                ',1)
INSERT INTO Pais VALUES('Paracel Islands                          ',1)
INSERT INTO Pais VALUES('Paraguai                                 ',1)
INSERT INTO Pais VALUES('Peru                                     ',1)
INSERT INTO Pais VALUES('Pitcairn                                 ',1)
INSERT INTO Pais VALUES('Polinésia Francesa                       ',1)
INSERT INTO Pais VALUES('Polónia                                  ',1)
INSERT INTO Pais VALUES('Porto Rico                               ',1)
INSERT INTO Pais VALUES('Portugal                                 ',1)
INSERT INTO Pais VALUES('Quénia                                   ',1)
INSERT INTO Pais VALUES('Quirguizistão                            ',1)
INSERT INTO Pais VALUES('Quiribáti                                ',1)
INSERT INTO Pais VALUES('Reino Unido                              ',1)
INSERT INTO Pais VALUES('República Centro-Africana                ',1)
INSERT INTO Pais VALUES('República Checa                          ',1)
INSERT INTO Pais VALUES('República Dominicana                     ',1)
INSERT INTO Pais VALUES('Roménia                                  ',1)
INSERT INTO Pais VALUES('Ruanda                                   ',1)
INSERT INTO Pais VALUES('Rússia                                   ',1)
INSERT INTO Pais VALUES('Salvador                                 ',1)
INSERT INTO Pais VALUES('Samoa                                    ',1)
INSERT INTO Pais VALUES('Samoa Americana                          ',1)
INSERT INTO Pais VALUES('Santa Helena                             ',1)
INSERT INTO Pais VALUES('Santa Lúcia                              ',1)
INSERT INTO Pais VALUES('São Cristóvão e Neves                    ',1)
INSERT INTO Pais VALUES('São Marinho                              ',1)
INSERT INTO Pais VALUES('São Pedro e Miquelon                     ',1)
INSERT INTO Pais VALUES('São Tomé e Príncipe                      ',1)
INSERT INTO Pais VALUES('São Vicente e Granadinas                 ',1)
INSERT INTO Pais VALUES('Sara Ocidental                           ',1)
INSERT INTO Pais VALUES('Seicheles                                ',1)
INSERT INTO Pais VALUES('Senegal                                  ',1)
INSERT INTO Pais VALUES('Serra Leoa                               ',1)
INSERT INTO Pais VALUES('Sérvia                                   ',1)
INSERT INTO Pais VALUES('Singapura                                ',1)
INSERT INTO Pais VALUES('Síria                                    ',1)
INSERT INTO Pais VALUES('Somália                                  ',1)
INSERT INTO Pais VALUES('Southern Ocean                           ',1)
INSERT INTO Pais VALUES('Spratly Islands                          ',1)
INSERT INTO Pais VALUES('Sri Lanca                                ',1)
INSERT INTO Pais VALUES('Suazilândia                              ',1)
INSERT INTO Pais VALUES('Sudão                                    ',1)
INSERT INTO Pais VALUES('Suécia                                   ',1)
INSERT INTO Pais VALUES('Suíça                                    ',1)
INSERT INTO Pais VALUES('Suriname                                 ',1)
INSERT INTO Pais VALUES('Svalbard e Jan Mayen                     ',1)
INSERT INTO Pais VALUES('Tailândia                                ',1)
INSERT INTO Pais VALUES('Taiwan                                   ',1)
INSERT INTO Pais VALUES('Tajiquistão                              ',1)
INSERT INTO Pais VALUES('Tanzânia                                 ',1)
INSERT INTO Pais VALUES('Território Britânico do Oceano Índico    ',1)
INSERT INTO Pais VALUES('Territórios Austrais Franceses           ',1)
INSERT INTO Pais VALUES('Timor Leste                              ',1)
INSERT INTO Pais VALUES('Togo                                     ',1)
INSERT INTO Pais VALUES('Tokelau                                  ',1)
INSERT INTO Pais VALUES('Tonga                                    ',1)
INSERT INTO Pais VALUES('Trindade e Tobago                        ',1)
INSERT INTO Pais VALUES('Tunísia                                  ',1)
INSERT INTO Pais VALUES('Turquemenistão                           ',1)
INSERT INTO Pais VALUES('Turquia                                  ',1)
INSERT INTO Pais VALUES('Tuvalu                                   ',1)
INSERT INTO Pais VALUES('Ucrânia                                  ',1)
INSERT INTO Pais VALUES('Uganda                                   ',1)
INSERT INTO Pais VALUES('União Europeia                           ',1)
INSERT INTO Pais VALUES('Uruguai                                  ',1)
INSERT INTO Pais VALUES('Usbequistão                              ',1)
INSERT INTO Pais VALUES('Vanuatu                                  ',1)
INSERT INTO Pais VALUES('Vaticano                                 ',1)
INSERT INTO Pais VALUES('Venezuela       ',1)
INSERT INTO Pais VALUES('Vietname                                 ',1)
INSERT INTO Pais VALUES('Wake Island                              ',1)
INSERT INTO Pais VALUES('Wallis e Futuna                          ',1)
INSERT INTO Pais VALUES('West Bank                                ',1)
INSERT INTO Pais VALUES('Zâmbia                                   ',1)
INSERT INTO Pais VALUES('Zimbabué                                 ',1)